<a href="https://colab.research.google.com/github/mohamed-ssafini/Mathematics-for-Deep-learning/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Intro to Matrices, Tensors and Images**

In [1]:
import numpy as np
import torch
import cv2
import matplotlib.pyplot as plt

In [13]:
# A matrix can be viewed as a 2-dimensional array of numbers.
# It can be thought of as 
# a collection of row vectors, or a collection of column vectors.

# For example, the training set for the cat-brain problem can be
# expressed as a matrix.
# Each input instance to the machine can be viewed as a vector
# represented by a row in this matrix.
# Our training set consists of 15 examples, where each example is
#  a row vectorof size 2. So there are 15 rows and 2 columns.

X = torch.tensor([[0.11, 0.09], [0.01, 0.02], [0.98, 0.91], [0.12, 0.21],
              [0.98, 0.99], [0.85, 0.87], [0.03, 0.14], [0.55, 0.45],
              [0.49, 0.51], [0.99, 0.01], [0.02, 0.89], [0.31, 0.47],
              [0.55, 0.29], [0.87, 0.76], [0.63, 0.24]])

In [3]:
#Output threat score will be modeled as a vector
y = torch.tensor([-0.8, -0.97, 0.89, -0.67, 0.97, 0.72, -0.83, 0.00, 0.00,
              0.00, -0.09, -0.22, -0.16, 0.63, 0.37])

In [4]:
# Shape of the matrix is depicted as a list.
# The first list element represents the number of rows,
# the second list element represents the number of columns.
# Our training set consists of 15 examples, where each example is a
#  row vector of size 2. So the shape is [15, 2].
print("Shape of the matrix is: {}".format(X.shape))

Shape of the matrix is: torch.Size([15, 2])


In [5]:
# Slicing the matrix
# The matrix can be sliced using the indices representing the axes. 

# Accessing individual elements of the matrix
# Each element is indexed by its row and column.
# Row, column indices start from 0

# Accessing first element of the matrix
first_element = X[0, 0]
print("First element: {}".format(first_element))

# Accessing 5th row, first column of the matrix
print("X[5][1]: {}".format(X[5][1]))

First element: 0.10999999940395355
X[5][1]: 0.8700000047683716


In [6]:
# Accessing the rows
# Note the each row corresponds to one training example in our case.
# The : is shorthand to access all the elements of the selected rows
# i.e X[0, :] is equivalent of X[0, 0:num_columns]
row_1 = X[0, :] # First row has an index of 0
row_2 = X[1, 0:2] # Second row has an index of 1
print("Row 1: {} Shape: {}".format(row_1, row_1.shape))
print("Row 2: {} Shape: {}".format(row_2, row_2.shape))

Row 1: tensor([0.1100, 0.0900]) Shape: torch.Size([2])
Row 2: tensor([0.0100, 0.0200]) Shape: torch.Size([2])


In [7]:
# Accessing the columns
# The columns can similarly be accessed using the second axis.
# Note that each column corresponds to one feature i.e hardness or
# sharpness in our case.
column_1 = X[:, 0] # First column has an index of 0
column_2 = X[:, 1] #Second column has an index of 1
print("Column 1: {} Shape: {}".format(column_1, column_1.shape))
print("Column 2: {} Shape: {}".format(column_2, column_2.shape))

Column 1: tensor([0.1100, 0.0100, 0.9800, 0.1200, 0.9800, 0.8500, 0.0300, 0.5500, 0.4900,
        0.9900, 0.0200, 0.3100, 0.5500, 0.8700, 0.6300]) Shape: torch.Size([15])
Column 2: tensor([0.0900, 0.0200, 0.9100, 0.2100, 0.9900, 0.8700, 0.1400, 0.4500, 0.5100,
        0.0100, 0.8900, 0.4700, 0.2900, 0.7600, 0.2400]) Shape: torch.Size([15])


In [11]:
# Ranges of rows and columns can be specified via colon operator to slice off (extract) sub-matrices
first_3_training_examples = X[:3, ]
first_3_training_examples1 = X[:3, :]

print(first_3_training_examples)
print(first_3_training_examples1)

tensor([[0.1100, 0.0900],
        [0.0100, 0.0200],
        [0.9800, 0.9100]])
tensor([[0.1100, 0.0900],
        [0.0100, 0.0200],
        [0.9800, 0.9100]])


In [16]:
print("Sharpness of 5-7 training examples is: {}".format(X[5:8, 1]))

Sharpness of 5-7 training examples is: tensor([0.8700, 0.1400, 0.4500])


In [17]:
#All images are tensors. RGB image of height H, width W is 3-tensor of shape [3, H, W]
I49 = np.array([[0, 8, 16, 24, 32, 40, 48, 56, 64],
[64,72, 80, 88, 96, 104, 112, 120, 128],
[128, 136, 144, 152, 160, 168, 176, 184, 192],
[192, 200, 208, 216, 224, 232, 240, 248, 255]],
dtype=np.uint8)

In [18]:
I49

array([[  0,   8,  16,  24,  32,  40,  48,  56,  64],
       [ 64,  72,  80,  88,  96, 104, 112, 120, 128],
       [128, 136, 144, 152, 160, 168, 176, 184, 192],
       [192, 200, 208, 216, 224, 232, 240, 248, 255]], dtype=uint8)